version: '3.3'
services:
  app-python:
    container_name: app-python
    image: terrytlx/app-python:1
    tty: true
    volumes:
      - ./python/src:/app
    ports:
      - "80:8000"
    networks:
      - ctf-network    
  db1:
    container_name: mysql
    image: terrytlx/game-db1:1
    volumes:
      - ./mysql/mysql_conf:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d      
    networks:
      - ctf-network
networks:
  ctf-network: